async function req(method, path, body) {
  const opts = { method, credentials: "include", headers: {} };
  if (body !== undefined) {
    opts.headers["Content-Type"] = "application/json";
    opts.body = JSON.stringify(body);
  }
  const res = await fetch("/api" + path, opts);
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw Object.assign(new Error(data.error || "Request failed"), data);
  return data;
}

export const authMe = () => req("GET", "/auth/me");
export const authLogin = (data) => req("POST", "/auth/login", data);
export const authRegister = (data) => req("POST", "/auth/register", data);
export const authLogout = () => req("POST", "/auth/logout");
export const updateProfile = (data) => req("PUT", "/users/me", data);
export const getMyReviews = () => req("GET", "/users/me/reviews");
export const listBooks = (params = {}) => req("GET", "/books?" + new URLSearchParams(params));
export const getBook = (id) => req("GET", `/books/${id}`);
export const addBook = (data) => req("POST", "/books", data);
export const searchOpenLib = (q) => req("GET", `/books/openlib/search?q=${encodeURIComponent(q)}`);
export const toggleFavorite = (bookId) => req("POST", `/books/${bookId}/favorite`);
export const listReviews = (bookId, sort) => req("GET", `/books/${bookId}/reviews?sort=${sort || "newest"}`);
export const createReview = (bookId, data) => req("POST", `/books/${bookId}/reviews`, data);
export const updateReview = (id, data) => req("PUT", `/reviews/${id}`, data);
export const deleteReview = (id) => req("DELETE", `/reviews/${id}`);
export const getReviewHistory = (id) => req("GET", `/reviews/${id}/history`);
export const toggleHelpful = (id) => req("POST", `/reviews/${id}/helpful`);
export const reportReview = (id, data) => req("POST", `/reviews/${id}/report`, data);
export const listClasses = () => req("GET", "/classes");
export const createClass = (data) => req("POST", "/classes", data);
export const updateClass = (id, data) => req("PUT", `/classes/${id}`, data);
export const deleteClass = (id) => req("DELETE", `/classes/${id}`);
export const joinClass = (code) => req("POST", "/classes/join", { code });
export const leaveClass = (id) => req("POST", `/classes/${id}/leave`);
export const getClassStudents = (classId) => req("GET", `/classes/${classId}/students`);
export const listAssignments = (classId) => req("GET", `/classes/${classId}/assignments`);
export const createAssignment = (classId, data) => req("POST", `/classes/${classId}/assignments`, data);
export const updateAssignment = (id, data) => req("PUT", `/assignments/${id}`, data);
export const deleteAssignment = (id) => req("DELETE", `/assignments/${id}`);
export const getBookAssignments = (bookId) => req("GET", `/books/${bookId}/assignments`);
export const getSubmissions = (assignmentId) => req("GET", `/assignments/${assignmentId}/submissions`);
export const saveGrade = (assignmentId, studentId, data) => req("PUT", `/assignments/${assignmentId}/grades/${studentId}`, data);
export const getClassProgress = (classId) => req("GET", `/classes/${classId}/my-progress`);
export const adminStats = () => req("GET", "/admin/stats");
export const adminListBooks = () => req("GET", "/admin/books");
export const adminHideBook = (id) => req("PUT", `/books/${id}/hide`);
export const adminBanBook = (id) => req("PUT", `/books/${id}/ban`);
export const adminRemoveBook = (id) => req("DELETE", `/admin/books/${id}`);
export const adminReviews = (params = {}) => req("GET", "/admin/reviews?" + new URLSearchParams(params));
export const setReviewVisibility = (id, data) => req("PUT", `/admin/reviews/${id}/visibility`, data);
export const adminForceEditReview = (id, data) => req("PUT", `/admin/reviews/${id}/force-edit`, data);
export const adminDeleteReview = (id) => req("DELETE", `/admin/reviews/${id}`);
export const adminDismissFlag = (id) => req("PUT", `/admin/reviews/${id}/dismiss-flag`, {});
export const adminReports = () => req("GET", "/admin/reports");
export const adminAutoReports = () => req("GET", "/admin/reports/auto");
export const handleReport = (id, data) => req("PUT", `/admin/reports/${id}`, data);
export const getFilterWords = () => req("GET", "/admin/filter-words");
export const updateFilterWords = (data) => req("PUT", "/admin/filter-words", data);
export const adminDeletedReviews = () => req("GET", "/admin/deleted-reviews");
export const adminPermanentDeleteReview = (historyId) => req("DELETE", `/admin/deleted-reviews/${historyId}`);
export const adminWipeBookData = (bookId) => req("DELETE", `/admin/books/${bookId}/wipe`);
export const getNotifications = () => req("GET", "/notifications");
export const getUnreadNotifCount = () => req("GET", "/notifications/unread-count");
export const markNotifRead = (id) => req("PUT", `/notifications/${id}/read`, {});
export const markAllNotifsRead = () => req("PUT", "/notifications/read-all", {});
export const deleteNotif = (id) => req("DELETE", `/notifications/${id}`);
export const deleteAllNotifs = () => req("DELETE", "/notifications");
export const adminUsers = () => req("GET", "/admin/users");
export const updateUserRole = (id, data) => req("PUT", `/admin/users/${id}/role`, data);
export const adminForceRename = (id, displayName) => req("PUT", `/admin/users/${id}/force-name`, { displayName });
export const adminDeleteUser = (id) => req("DELETE", `/admin/users/${id}`);